### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by hamoude321** [LITdevs/vukkybox#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i cant login using discord, google and github, it used to work but now it doesnt

### Expected Behavior

for it to show me a popup to link my discord then redirected back to the website and logged in

### Steps To Reproduce

1. login
2. issue found

### Environment

```markdown
- OS: Windows 10
- Browser: firefox
- Login method: All(my existing one is discord)
```

**Comment by Vukkyy** [comment]
User said that this was done by an extension

~~hamood habibi~~
