### ISSUE TITLE
Store Vukky unbox sound effects in vukkies.json

### ISSUE THREAD

**Issue by Vukkyy** [LITdevs/vukkybox#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

Instead of creating a big pile of spaghetti & Vukkies in the view and buyBox pages, we should give every Vukky with a custom sound effect an "audio" property in vukkies.json.

### Why should this be implemented?

This would allow us to not turn view and buyBox into a big pile of spaghetti & Vukkies.

**Comment by vtheskeleton** [comment]
This has been implemented, and confirmed working on both view and buyBox.
