### ISSUE TITLE
Allow custom styling for Vukky names and descriptions

### ISSUE THREAD

**Issue by Vukkyy** [LITdevs/vukkybox#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

Allowing custom styling for Vukky names and descriptions would allow us to color Vukky names (especially logo-related Vukkies) and would fix the long-lasting issue of the terrible Miner Vukky and its link.

### Why should this be implemented?

More creativity! It would spice things up a bit.

### Anything else?

![image](https://user-images.githubusercontent.com/46850780/146770577-669a6eb0-d584-47a1-bd9b-f23b87a552d9.png)

**Comment by vtheskeleton** [comment]
Added and confirmed working
