### ISSUE TITLE
Beggar's Box

### ISSUE THREAD

**Issue by Mou-Ikkai** [LITdevs/vukkybox#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

"Beggar's Box" - Even cheaper than a regular box, but it gives only low ranking vukkies, no rare or higher for you! (Common 90, uncommon 10), beggars can't be choosers. (Maybe 1-0.1 in price)

### Why should this be implemented?

It can always help when you need the Common or Uncommon collection to be fully completed, along with getting those last few Vukkybux to have a good use instead of staying there.

**Comment by Vukkyy** [comment]
This should be fairly easy to do, except for the image! Do you have any ideas for that? @Mou-Ikkai?

**Comment by Mou-Ikkai** [comment]
@Vukkyy I'd say, maybe like a poor vukky in a tipped over box? Kind of like Homeless Squidward lol.

**Comment by vtheskeleton** [comment]
implemented
