### ISSUE TITLE
Hide refunded amount until box is open 

### ISSUE THREAD

**Issue by vtheskeleton** [LITdevs/vukkybox#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You can see if you got a dupe based on if you got a refund

### Expected Behavior

Don't show it until the box is open like before

### Steps To Reproduce

1. open box
2. get dupe and see your moneys go up
3. cringe because you got spoiled!

### Environment

```markdown
- OS:widnwod
- Browser:chreom
- Login method:discorsds
```

### Anything else?

monke

**Comment by Vukkyy** [comment]
Invalid issue. Please use the template properly.
