### ISSUE TITLE
Hide refunded balance until box open

### ISSUE THREAD

**Issue by vtheskeleton** [LITdevs/vukkybox#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You can see if you got a dupe based on if you got a refund

### Expected Behavior

Don't show it until the box is open like before

### Steps To Reproduce

1. open box
2. get dupe and see your moneys go up
3. cringe because you got spoiled!

### Environment

Any

**Comment by Vukkyy** [comment]
How the FUCK do i debug this

**Comment by Vukkyy** [comment]
wait did you label this as a bug

**Comment by vtheskeleton** [comment]
> How the FUCK do i debug this

you are not assigned to this issue

**Comment by Vukkyy** [comment]
i forgot

**Comment by Vukkyy** [comment]
> > How the FUCK do i debug this
> 
> you are not assigned to this issue

neither are you

**Comment by Vukkyy** [comment]
oh fuck you then

**Comment by Vukkyy** [comment]
but this a bug though

**Comment by Vukkyy** [comment]
now it's nothing

**Comment by Vukkyy** [comment]
oh

**Comment by Vukkyy** [comment]
![image](https://user-images.githubusercontent.com/46850780/146916446-c0e2b622-b1ca-4e9f-9943-3ce2af562e2f.png)
no it's not

**Comment by Vukkyy** [comment]
oh

**Comment by vtheskeleton** [comment]
![image](https://user-images.githubusercontent.com/47392011/146916471-83d5d4d3-5391-45cb-a8c7-f07a43dcc9da.png)

**Comment by vtheskeleton** [comment]
now if you would kindly bugger off

**Comment by Vukkyy** [comment]
ok

**Comment by Vukkyy** [comment]
now how the FUCK do i clear these comments

**Comment by Vukkyy** [comment]
just make a new issue? i don't know

**Comment by Vukkyy** [comment]
@memedmusic water you doing here

**Comment by vtheskeleton** [comment]
Something very funky happening with this and i have no clue why my attempted fixes did not work

**Comment by vtheskeleton** [comment]
Should actually be fixed finally
