### ISSUE TITLE
Cannot access gallery if user owns no duplicates

### ISSUE THREAD

**Issue by memedmusic** [LITdevs/vukkybox#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a user has no duplicate vukkies then they are left hanging in the "Printing Vukkies" screen. This error is outputted to console: "Uncaught SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at gallery:210"

### Expected Behavior

The gallery loads

### Steps To Reproduce

1. Create alt account
2. Open 1 box (doesnt matter what type)
3. go to gallery
4. notice how gallery doesnt load
5. open boxes until you get a duplicate
6. go to gallery again
7. notice how the gallery loads now

### Environment

```markdown
- OS: Windows 11 10.0.22000
- Browser: Chrome 96.0.4664.110
- Login method: Any
```

### Anything else?

Without duplicate vukkies (i opened 1 box)
![image](https://user-images.githubusercontent.com/55370047/147019666-a8d06533-fcec-47a9-bb74-ba62d336a2bc.png)

With duplicate vukkies
![image](https://user-images.githubusercontent.com/55370047/147019767-a57beea1-15bb-4827-bac6-40436ec8dd10.png)

**Comment by vtheskeleton** [comment]
oops lol

**Comment by vtheskeleton** [comment]
fixed
