### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Vukkyy** [LITdevs/vukkybox#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

Add leaderboards to the game such as boxes opened and how many Vukkies people have (per rarity)

### Why should this be implemented?

It would make the game feel a bit less lonely, I suppose. And it's cool! Come on! We have some data, put it to use!

**Comment by vtheskeleton** [comment]
Current list of considered boards:

- uniqueVukkies
- Vukkies in each rarity
- boxesOpened
- balance (Could be sketchy)
