### ISSUE TITLE
Earning vukkies

### ISSUE THREAD

**Issue by lilmelon21** [LITdevs/vukkybox#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

You guys should make it when I have collected a full list of vukkies for example : godly vukkies.We don't receive anymore vukkies from that category.

### Why should this be implemented?

bec kool :D

### Anything else?

![image](https://user-images.githubusercontent.com/97390168/148682222-842330a6-a2d8-45ad-8f48-4fc17f997906.png)

**Comment by vtheskeleton** [comment]
This goes against the gacha game style

**Comment by Vukkyy** [comment]
Sincerely,Sincerely,

Vukky!
Sincerely,Sincerely,Sincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkied

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkied

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkied

Discord: Vukky#1550 or join server
Twitter: @vukkied

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkiedSincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkiedSincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkiedSincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkiedSincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkiedSincerely,Sincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkied

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkiedSincerely,

Vukky!


Discord: Vukky#1550 or join server
Twitter: @vukkied
