### ISSUE TITLE
wily wonnla

### ISSUE THREAD

**Issue by sydzney** [LITdevs/vukkybox#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

everything in here is edible, even i am, but that is called cannibalism and is in fact frowned upon in most countries

hi welcome to chilis

"i chOoSe mAh famLey"

ACCEPT YOURSELF. LOVE YOURSELF. ACCEPT YOURSELF.

imma bad bitch u cant kill me

### Expected Behavior

the next time you see a candy on the pavement, dont eat it. its a bug.

### Steps To Reproduce

sharkboy and labagurl

### Environment

```markdown
i aree
```

### Anything else?

good morning starshine and the world says HELLO

**Comment by vtheskeleton** [comment]
hilarious
