### ISSUE TITLE
Account linking

### ISSUE THREAD

**Issue by vtheskeleton** [LITdevs/vukkybox#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your suggestion

Allow users to link multiple accounts to the same vukkybox account	

### Why should this be implemented?

The frontend has this implemented, just disabled. The backend has most of it implemented too.
This feature has been in the plans since day -100
I see no reason why we shouldn't add this

### Anything else?

![image](https://user-images.githubusercontent.com/47392011/150691112-6b67963d-64de-4ef6-8379-c35db95afe11.png)
Imag

**Comment by lxjv** [comment]
do it

**Comment by vtheskeleton** [comment]
with litauth being released, this has become irrelevant

**Comment by Vukkyy** [comment]
wrong close reason

**Comment by vtheskeleton** [comment]
i just wrote a comment and clicked close with comment
